[build]
  base = ""
  publish = "build"
  command = "yarn run build"
  # functions = "project/functions/"

  [build.processing]
    skip_processing = false
  [build.processing.css]
    bundle = true
    minify = false
  [build.processing.js]
    bundle = true
    minify = false
  [build.processing.html]
    pretty_urls = true
  [build.processing.images]
    compress = true


[[headers]]
  for = "/*"

  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    X-Permitted-Cross-Domain-Policies = "none"
    Referrer-Policy = "SAME-ORIGIN"

[[headers]]
  for = "/static/*"

  [headers.values]
    Cache-Control = "public,max-age=31536000,immutable"


[[redirects]]
  from = "/api/*"
  to = "https://cms.castelnuovo.xyz/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
